pub(crate) const KNOWN_LIBRARIES: &[&str] = &[
    "react",
    "vue",
    "svelte",
    "angular",
    "next.js",
    "nextjs",
    "nuxt",
    "node",
    "node.js",
    "nodejs",
    "deno",
    "bun",
    "typescript",
    "javascript",
    "rust",
    "go",
    "golang",
    "python",
    "java",
    "kotlin",
    "swift",
    "ruby",
    "php",
    "c++",
    "csharp",
    "elixir",
    "scala",
    "django",
    "flask",
    "fastapi",
    "express",
    "koa",
    "nest",
    "nestjs",
    "axum",
    "actix",
    "tokio",
    "rocket",
    "warp",
    "spring",
    "rails",
    "postgres",
    "postgresql",
    "mysql",
    "sqlite",
    "mongodb",
    "redis",
    "kafka",
    "rabbitmq",
    "docker",
    "kubernetes",
    "k8s",
    "terraform",
    "ansible",
    "helm",
    "webpack",
    "vite",
    "esbuild",
    "rollup",
    "parcel",
    "turbopack",
    "jest",
    "vitest",
    "mocha",
    "pytest",
    "playwright",
    "cypress",
    "eslint",
    "prettier",
    "tsc",
    "babel",
    "swc",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "openai",
    "anthropic",
    "claude",
    "gpt",
    "llama",
    "qwen",
    "deepseek",
    "tailwind",
    "sass",
    "less",
    "prisma",
    "drizzle",
    "sequelize",
    "typeorm",
    "sqlx",
    "diesel",
    "graphql",
    "trpc",
    "grpc",
    "rest",
    "aws",
    "gcp",
    "azure",
    "vercel",
    "netlify",
    "cloudflare",
    "pnpm",
    "npm",
    "yarn",
    "cargo",
    "pip",
    "poetry",
    "uv",
    "corepack",
];

pub(crate) const KNOWN_COMMANDS: &[&str] = &[
    "pnpm install",
    "pnpm test",
    "pnpm build",
    "pnpm dev",
    "pnpm run",
    "npm install",
    "npm test",
    "npm run",
    "npm ci",
    "yarn install",
    "yarn test",
    "yarn build",
    "cargo build",
    "cargo test",
    "cargo run",
    "cargo check",
    "cargo clippy",
    "cargo fmt",
    "git push",
    "git pull",
    "git commit",
    "git rebase",
    "git merge",
    "git reset",
    "docker build",
    "docker run",
    "docker compose",
];

pub(crate) const KNOWN_CONCEPTS: &[&str] = &[
    "authentication",
    "auth",
    "login",
    "logout",
    "signup",
    "signin",
    "authorization",
    "permission",
    "rbac",
    "oauth",
    "jwt",
    "deployment",
    "deploy",
    "pipeline",
    "database",
    "migration",
    "schema",
    "query",
    "cache",
    "caching",
    "performance",
    "latency",
    "throughput",
    "testing",
    "refactor",
    "refactoring",
    "bug",
    "feature",
    "leak",
    "crash",
    "deadlock",
    "api",
    "endpoint",
    "route",
    "controller",
    "middleware",
    "frontend",
    "backend",
    "fullstack",
    "trait",
    "interface",
];

pub(crate) const FILE_EXTS: &[&str] = &[
    ".rs", ".ts", ".tsx", ".js", ".jsx", ".py", ".go", ".java", ".kt", ".rb", ".php", ".cs",
    ".cpp", ".h", ".hpp", ".swift", ".toml", ".json", ".yaml", ".yml", ".md", ".sql", ".sh",
    ".bash", ".html", ".css", ".scss", ".vue", ".svelte",
];
